server {
    listen 80;
    server_name localhost;

    location /videos/ {
        alias /usr/share/nginx/html/videos/;
        index index.html;
        try_files $uri $uri/ /videos/index.html;
    }

    # Redirect root traffic to /videos/
    location = / {
        return 301 /videos/;
    }
}
